[package]
name = "async-safe-defer"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
tokio = { version = "1.44.2", features = ["rt", "macros"] }

[features]
default = []
no_alloc = []
